/**
 * Load and compile the host agent directory (convention: ./agent).
 *
 * Layout:
 *   agent/
 *     SOUL.md
 *     AGENTS.md
 *     skills/<name>/...
 */

import { mkdir, readdir, readFile, stat, writeFile } from "node:fs/promises";
import { dirname, extname, join, relative, sep } from "node:path";
import type { AgentBundle, SkillSeed } from "@socialrobot-io/agent-kit-core";

const DEFAULT_AGENT_DIR = "./agent";

async function readOptional(path: string): Promise<string | undefined> {
  try {
    return await readFile(path, "utf8");
  } catch (err) {
    const code = (err as NodeJS.ErrnoException).code;
    if (code === "ENOENT") return undefined;
    throw err;
  }
}

async function loadSkillFolder(skillDir: string): Promise<Record<string, string>> {
  const files: Record<string, string> = {};

  async function walk(dir: string): Promise<void> {
    let entries;
    try {
      entries = await readdir(dir, { withFileTypes: true });
    } catch (err) {
      const code = (err as NodeJS.ErrnoException).code;
      if (code === "ENOENT") throw new Error(`skill folder not found: ${skillDir}`);
      throw err;
    }
    for (const entry of entries) {
      const abs = join(dir, entry.name);
      if (entry.isDirectory()) {
        await walk(abs);
        continue;
      }
      if (!entry.isFile()) continue;
      const rel = relative(skillDir, abs).split(sep).join("/");
      files[rel] = await readFile(abs, "utf8");
    }
  }

  const st = await stat(skillDir);
  if (!st.isDirectory()) throw new Error(`skill path is not a directory: ${skillDir}`);
  await walk(skillDir);
  return files;
}

async function listSkillDirs(skillsRoot: string): Promise<string[]> {
  let entries;
  try {
    entries = await readdir(skillsRoot, { withFileTypes: true });
  } catch (err) {
    const code = (err as NodeJS.ErrnoException).code;
    if (code === "ENOENT") return [];
    throw err;
  }
  return entries.filter((e) => e.isDirectory() && !e.name.startsWith(".")).map((e) => e.name);
}

/** Read `agent/` into an {@link AgentBundle}. */
export async function loadAgent(dir: string = DEFAULT_AGENT_DIR): Promise<AgentBundle> {
  const soul = await readOptional(join(dir, "SOUL.md"));
  const agentsMd = await readOptional(join(dir, "AGENTS.md"));
  const skills: SkillSeed[] = [];

  for (const name of await listSkillDirs(join(dir, "skills"))) {
    const files = await loadSkillFolder(join(dir, "skills", name));
    if (!files["SKILL.md"] && !Object.keys(files).some((k) => k.endsWith("/SKILL.md"))) {
      throw new Error(`skill '${name}' has no SKILL.md under ${join(dir, "skills", name)}`);
    }
    skills.push({ name, files, tier: "agent" });
  }

  if (!soul && !agentsMd && skills.length === 0) {
    throw new Error(`loadAgent found nothing under '${dir}'`);
  }

  return { soul, agentsMd, skills };
}

export interface CompileAgentOptions {
  /** Agent authoring directory. Default `./agent`. */
  dir?: string;
  /**
   * Output path. `.ts` / `.js` → module exporting `agent`.
   * `.json` → JSON document.
   */
  outFile: string;
}

function emitTypeScript(bundle: AgentBundle): string {
  const body = JSON.stringify(bundle, null, 2);
  return (
    "/* AUTO-GENERATED by compileAgent — do not edit. */\n" +
    "import type { AgentBundle } from \"@socialrobot-io/agent-kit-core\";\n\n" +
    `export const agent = ${body} as const satisfies AgentBundle;\n` +
    "export default agent;\n"
  );
}

/**
 * Compile `agent/` to an importable module for any bundler/runtime.
 *
 * ```ts
 * await compileAgent({ outFile: "./src/generated/agent.ts" });
 * // createTenantHome({ tenantId, agent })
 * ```
 */
export async function compileAgent(opts: CompileAgentOptions): Promise<AgentBundle> {
  if (!opts.outFile?.trim()) throw new Error("compileAgent requires outFile");
  const bundle = await loadAgent(opts.dir ?? DEFAULT_AGENT_DIR);
  const ext = extname(opts.outFile).toLowerCase();
  let contents: string;
  if (ext === ".json") {
    contents = `${JSON.stringify(bundle, null, 2)}\n`;
  } else if (ext === ".ts" || ext === ".mts" || ext === ".cts" || ext === ".js" || ext === ".mjs") {
    contents = emitTypeScript(bundle);
  } else {
    throw new Error(`compileAgent: unsupported outFile extension '${ext}' (use .ts, .js, or .json)`);
  }
  await mkdir(dirname(opts.outFile), { recursive: true });
  await writeFile(opts.outFile, contents, "utf8");
  return bundle;
}
